[project]
name = "g_structure"
version = "0.1.0"
description = "Visualization utilities for transformer analysis"
requires-python = ">=3.10"
dependencies = [
    "plotly>=5.24.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"